# GamerX OS · live ISO SDDM config
# Autologin live user into Hyprland; theme set to gamerx.

[General]
Numlock=on

[Autologin]
User=gamerx
Session=hyprland.desktop
Relogin=false

[Theme]
Current=gamerx

[Users]
MaximumUid=60000
MinimumUid=1000
