---
efiSystemPartition:    "/boot/efi"
userSwapChoices:
    - none
    - small
    - suspend
    - file
drawNestedPartitions:   true
alwaysShowPartitionLabels: true
defaultFileSystemType:  "btrfs"
availableFileSystemTypes: ["btrfs","ext4","xfs","f2fs"]
initialPartitioningChoice: erase
initialSwapChoice: none
