---
services:
    - name: NetworkManager
      mandatory: false
    - name: sddm
      mandatory: false
    - name: bluetooth
      mandatory: false
targets:
    - name: graphical
      mandatory: true
