---
showSupportUrl:         true
showKnownIssuesUrl:     false
showReleaseNotesUrl:    false
showDonateUrl:          false

requirements:
    requiredStorage:    16.0
    requiredRam:        2.0
    internetCheck:      false
    check:
        - storage
        - ram
        - power
        - screen
        - root
    required:
        - storage
        - ram
        - root
